baseURL: "https://tpriests-weird-blog.onrender.com"
languageCode: en-us
title: TPriest's Weird Blog
paginate: 6
theme: PaperMod
enableRobotsTXT: true
enableEmoji: true
# copyright: = [en1tan.github.io](https://en1tan.github.io)
minify:
  disableXML: false
params:
  env: production
  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://avatars.githubusercontent.com/u/16443589?v=4"
    favicon16x16: "https://avatars.githubusercontent.com/u/16443589?v=4"
    favicon32x32: "https://avatars.githubusercontent.com/u/16443589?v=4"
    apple_touch_icon: "https://avatars.githubusercontent.com/u/16443589?v=4"
    safari_pinned_tab: "https://avatars.githubusercontent.com/u/16443589?v=4"
  dateForm: "Jan 2, 2006"
  dateFormShort: Jan 2
  dateFormNum: 2006/01/02
  dateForNumTime: "2006/01/02 15:04"
  images: ["https://avatars.githubusercontent.com/u/16443589?v=4"]
  keywords:
    - blog
    - weird
    - portfolio
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: true
  showtoc: true
  label:
    text: "Home"
    icon: https://avatars.githubusercontent.com/u/16443589?v=4
    iconHeight: 35
  homeInfoParams:
    Title: "Hello there \U0001F44B"
  socialIcons:
    - name: twitter
      url: "https://twitter.com/dtechpriest"
    - name: youtube
      url: "https://www.youtube.com/channel/UCIbM0RD_zpIML-RJ5zO6P7A"
    - name: github
      url: "https://github.com/en1tan"
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
    - identifier: categories
      name: Categories
      url: /categories/
    - identifier: tags
      name: Tags
      url: /tags/
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
pygmentUseClasses: true
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
